feat: payment intent full flow
Lomray-Software/microservices pull request #10
Opened 2023-04-07 09:18 UTC by Andrey-Lavnik

2023-04-07 09:55 UTC, MatthewPattell requested changes

2023-04-07 09:55 UTC, MatthewPattell commented on microservices/payment/src/entities/connect-account.ts
> +class ConnectAccount {
remove

2023-04-07 09:55 UTC, MatthewPattell commented on microservices/payment/src/methods/index.ts
> +    connectAccount: {
remove

2023-04-07 09:55 UTC, MatthewPattell commented on microservices/payment/src/methods/stripe/connect-account/create.ts
microservices/payment/src/methods/stripe/connect-account.ts

2023-04-07 09:55 UTC, MatthewPattell commented on microservices/payment/src/methods/stripe/connect-account/create.ts
> +class ConnectAccountCreateInput {
```suggestion
class ConnectAccountInput {
```

2023-04-07 09:55 UTC, MatthewPattell commented on microservices/payment/src/methods/stripe/connect-account/create.ts
> +class ConnectAccountCreateOutput {
```suggestion
class ConnectAccountOutput {
```

2023-04-07 09:55 UTC, MatthewPattell commented on microservices/payment/src/methods/stripe/connect-account/crud.ts
> +const crud = Endpoint.controller(() => getRepository(ConnectAccount), {
remove

2023-04-07 09:55 UTC, MatthewPattell commented on microservices/payment/src/services/payment-gateway/abstract.ts
> +  }
move to separated service
microservices/payment/src/services/stripe/connect-account.ts

2023-04-07 09:55 UTC, MatthewPattell commented on microservices/payment/src/services/payment-gateway/stripe.ts
> +  }
move to service

2023-04-07 09:55 UTC, MatthewPattell commented on microservices/payment/src/entities/connect-account.ts
> +  connectAccountId: string;
microservices/microservices/payment/src/entities/customer.ts

```
interface ICustomerParams {
  accountId?: string;
}

@IsObject()
params: ICustomerParams; // json
```

2023-04-24 17:15 UTC, Andrey-Lavnik commented on microservices/payment/src/methods/index.ts
> +    connectAccount: {
done

2023-04-24 17:15 UTC, Andrey-Lavnik commented on microservices/payment/src/entities/connect-account.ts
> +class ConnectAccount {
done

2023-04-24 17:15 UTC, Andrey-Lavnik commented on microservices/payment/src/entities/connect-account.ts
> +  connectAccountId: string;
done

2023-04-24 17:15 UTC, Andrey-Lavnik commented on microservices/payment/src/methods/stripe/connect-account/create.ts
done

2023-04-24 17:16 UTC, Andrey-Lavnik commented on microservices/payment/src/methods/stripe/connect-account/create.ts
> +class ConnectAccountCreateInput {
done

2023-04-24 18:33 UTC, MatthewPattell requested changes
a lot of stule guide issues

2023-04-24 18:33 UTC, MatthewPattell commented on microservices/payment/src/methods/stripe/connect-account.ts
> +  returnUrl: string;
```suggestion
  @IsString()
  userId: string;
  
  @IsString()
  email: string;
  
  @IsString()
  refreshUrl: string;
  
  @IsString()
  returnUrl: string;
```

2023-04-28 13:19 UTC, MatthewPattell approved these changes

2023-04-28 14:13 UTC, merged