feat: created adding payment method flow
Lomray-Software/microservices pull request #7
Opened 2023-03-25 23:52 UTC by vackca

2023-03-26 00:01 UTC, vackca commented
I am gonna add tests in the next PR

2023-03-27 10:11 UTC, MatthewPattell requested changes

2023-03-27 10:11 UTC, MatthewPattell commented on microservices/payment/src/interfaces/stripe-payment-options.ts
> +import StripePaymentMethods from '@constants/stripe-payment-methods';
```suggestion
import type StripePaymentMethods from '@constants/stripe-payment-methods';
```

2023-03-27 10:11 UTC, MatthewPattell commented on microservices/payment/src/interfaces/stripe-payment-options.ts
> +import Stripe from 'stripe';
```suggestion
import type Stripe from 'stripe';
```

2023-03-27 10:11 UTC, MatthewPattell commented on microservices/payment/src/interfaces/stripe-payment-options.ts
> +export default interface IStripePaymentOptions {
```suggestion
export default interface IStripeOptions {
```

2023-03-27 10:11 UTC, MatthewPattell commented on microservices/payment/src/methods/customer/create.ts
> +  userId: string;
add decorator

2023-03-27 10:11 UTC, MatthewPattell commented on microservices/payment/src/methods/customer/create.ts
> +import { ICustomerParams } from '@services/payment-gateway/abstract';
```suggestion
import type { ICustomerParams } from '@services/payment-gateway/abstract';
```

2023-03-27 10:11 UTC, MatthewPattell commented on microservices/payment/src/services/payment-gateway/stripe.ts
> +  async createCustomer(userId: string): Promise<Customer> {
```suggestion
 public async createCustomer(userId: string): Promise<Customer> {
```

2023-03-27 10:11 UTC, MatthewPattell commented on microservices/payment/src/services/payment-gateway/abstract.ts
> +}
```suggestion
```

2023-03-27 10:11 UTC, MatthewPattell commented on microservices/payment/src/services/payment-gateway/abstract.ts
> +export type TPaymentEntity = Stripe;
```suggestion
```

2023-03-27 10:11 UTC, MatthewPattell commented on microservices/payment/src/services/payment-gateway/abstract.ts
> +
```suggestion
```

2023-03-27 10:11 UTC, MatthewPattell commented on microservices/payment/src/services/payment-gateway/abstract.ts
> +    paymentOptions: Abstract['paymentOptions'],
```suggestion
    manager: EntityManager,
```

2023-03-27 10:11 UTC, MatthewPattell commented on microservices/payment/src/services/payment-gateway/abstract.ts
> +  public abstract createSetupIntent(userId: string): Promise<string | null>;
```suggestion
```

2023-03-27 10:11 UTC, MatthewPattell commented on microservices/payment/src/services/payment-gateway/factory.ts
> +        throw new Error(`Payment options for stripe are not provided`);
```suggestion
        if (!paymentOptions) {
            throw new Error('Payment options for stripe are not provided');
        }

         return new Stripe(manager, paymentProvider, paymentOptions);
```

2023-03-27 10:11 UTC, MatthewPattell commented on microservices/payment/src/services/payment-gateway/factory.ts
> +import StripeEntity from './stripe';
```suggestion
import Stripe from './stripe';
```

2023-03-27 10:11 UTC, MatthewPattell commented on microservices/payment/src/services/payment-gateway/factory.ts
> +import { EntityManager } from 'typeorm';
```suggestion
import type { EntityManager } from 'typeorm';
```

2023-03-27 10:11 UTC, MatthewPattell commented on microservices/payment/src/services/payment-gateway/stripe.ts
> +import StripeEntity from 'stripe';
```suggestion
import StripeSDK from 'stripe';
```

2023-03-27 10:11 UTC, MatthewPattell commented on microservices/payment/src/methods/index.ts
> +    },
```suggestion
```

2023-03-27 10:11 UTC, MatthewPattell commented on microservices/payment/src/methods/customer/create.ts
> +class CustomerCreateInput implements ICustomerParams {
```suggestion
class CustomerCreateInput {
```

2023-03-27 10:11 UTC, MatthewPattell commented on microservices/payment/src/methods/setup-intent/create.ts
> +class CreateSetupIntentInput implements ISetupIntentParams {
```suggestion
class CreateSetupIntentInput {
```

2023-03-27 10:11 UTC, MatthewPattell commented on microservices/payment/src/methods/setup-intent/create.ts
> +import { Endpoint } from '@lomray/microservice-helpers';
microservices/payment/src/methods/setup-intent/create.ts => microservices/payment/src/methods/stripe/setup-intent.ts

2023-03-27 10:11 UTC, MatthewPattell commented on microservices/payment/src/services/payment-gateway/stripe.ts
> +  async createSetupIntent(userId: string): Promise<string | null> {
```suggestion
public  async setupIntent(userId: string): Promise<string | null> {
```

2023-03-27 10:11 UTC, MatthewPattell commented on microservices/payment/src/methods/setup-intent/create.ts
> +    const service = await Factory.create(getManager());
```suggestion
    const service = await Factory.create(getManager()) as Stripe;
```

2023-03-27 13:20 UTC, vackca commented on microservices/payment/src/interfaces/stripe-payment-options.ts
> +import StripePaymentMethods from '@constants/stripe-payment-methods';
added

2023-03-27 13:20 UTC, vackca commented on microservices/payment/src/interfaces/stripe-payment-options.ts
> +import Stripe from 'stripe';
added

2023-03-27 13:20 UTC, vackca commented on microservices/payment/src/interfaces/stripe-payment-options.ts
> +export default interface IStripePaymentOptions {
changed

2023-03-27 13:20 UTC, vackca commented on microservices/payment/src/methods/customer/create.ts
> +import { ICustomerParams } from '@services/payment-gateway/abstract';
added

2023-03-27 13:21 UTC, vackca commented on microservices/payment/src/methods/index.ts
> +    },
deleted

2023-03-27 13:21 UTC, vackca commented on microservices/payment/src/methods/customer/create.ts
> +class CustomerCreateInput implements ICustomerParams {
changed

2023-03-27 13:21 UTC, vackca commented on microservices/payment/src/methods/setup-intent/create.ts
> +class CreateSetupIntentInput implements ISetupIntentParams {
deleted

2023-03-27 13:21 UTC, vackca commented on microservices/payment/src/methods/setup-intent/create.ts
> +import { Endpoint } from '@lomray/microservice-helpers';
renamed

2023-03-27 13:22 UTC, vackca commented on microservices/payment/src/services/payment-gateway/stripe.ts
> +  async createSetupIntent(userId: string): Promise<string | null> {
added

2023-03-27 13:22 UTC, vackca commented on microservices/payment/src/methods/setup-intent/create.ts
> +    const service = await Factory.create(getManager());
added

2023-03-27 13:22 UTC, vackca commented on microservices/payment/src/services/payment-gateway/stripe.ts
> +import StripeEntity from 'stripe';
renamed

2023-03-27 13:22 UTC, vackca commented on microservices/payment/src/services/payment-gateway/abstract.ts
> +  public abstract createSetupIntent(userId: string): Promise<string | null>;
deleted

2023-03-27 13:22 UTC, vackca commented on microservices/payment/src/services/payment-gateway/factory.ts
> +        throw new Error(`Payment options for stripe are not provided`);
changed

2023-03-27 13:23 UTC, vackca commented on microservices/payment/src/services/payment-gateway/factory.ts
> +import StripeEntity from './stripe';
changed

2023-03-27 13:23 UTC, vackca commented on microservices/payment/src/services/payment-gateway/factory.ts
> +import { EntityManager } from 'typeorm';
added

2023-03-27 13:23 UTC, vackca commented on microservices/payment/src/services/payment-gateway/abstract.ts
> +    paymentOptions: Abstract['paymentOptions'],
deleted

2023-03-27 13:23 UTC, vackca commented on microservices/payment/src/services/payment-gateway/abstract.ts
> +
deleted

2023-03-27 13:23 UTC, vackca commented on microservices/payment/src/services/payment-gateway/abstract.ts
> +export type TPaymentEntity = Stripe;
deleted

2023-03-27 13:28 UTC, vackca commented on microservices/payment/src/services/payment-gateway/stripe.ts
> +  async createCustomer(userId: string): Promise<Customer> {
added

2023-03-27 13:28 UTC, vackca commented on microservices/payment/src/services/payment-gateway/abstract.ts
> +}
deleted

2023-03-27 13:41 UTC, vackca commented on microservices/payment/src/methods/customer/create.ts
> +  userId: string;
added

2023-03-27 13:59 UTC, MatthewPattell requested changes
update permissions?

2023-03-27 13:59 UTC, MatthewPattell commented on microservices/payment/src/interfaces/remote-config.ts
> +import TPaymentOptions from '@interfaces/payment-options';
```suggestion
import type TPaymentOptions from '@interfaces/payment-options';
```

2023-03-27 13:59 UTC, MatthewPattell commented on microservices/payment/src/methods/stripe/setup-intent.ts
> +}
where validation decorators?

2023-03-27 13:59 UTC, MatthewPattell commented on microservices/payment/src/methods/stripe/setup-intent.ts
> +    const service = (await Factory.create(getManager())) as Stripe;
we should add `if` and check payment provider === 'stripe'

2023-03-27 13:59 UTC, MatthewPattell commented on microservices/payment/src/services/payment-gateway/factory.ts
> +        return new Stripe(manager, paymentProvider, paymentOptions);
```suggestion
        return new Stripe(manager, paymentProvider, paymentOptions);

```

2023-03-27 13:59 UTC, MatthewPattell commented on microservices/payment/src/services/payment-gateway/stripe.ts
> +import { EntityManager } from 'typeorm';
```suggestion
import type { EntityManager } from 'typeorm';
```

2023-03-27 13:59 UTC, MatthewPattell commented on microservices/payment/src/services/payment-gateway/stripe.ts
> +  public async createCustomer(userId: string): Promise<Customer> {
detect existing customer??

2023-03-27 13:59 UTC, MatthewPattell commented on microservices/payment/src/services/payment-gateway/stripe.ts
> +    paymentOptions: TPaymentOptions,
use stripe interface directly?

2023-03-27 14:09 UTC, vackca commented on microservices/payment/src/interfaces/remote-config.ts
> +import TPaymentOptions from '@interfaces/payment-options';
added

2023-03-27 14:11 UTC, vackca commented on microservices/payment/src/methods/stripe/setup-intent.ts
> +}
added

2023-03-27 14:23 UTC, vackca commented on microservices/payment/src/services/payment-gateway/factory.ts
> +        return new Stripe(manager, paymentProvider, paymentOptions);
added

2023-03-27 14:23 UTC, vackca commented on microservices/payment/src/methods/stripe/setup-intent.ts
> +    const service = (await Factory.create(getManager())) as Stripe;
added

2023-03-27 14:24 UTC, vackca commented on microservices/payment/src/services/payment-gateway/stripe.ts
> +import { EntityManager } from 'typeorm';
added

2023-03-27 14:40 UTC, vackca commented on microservices/payment/src/services/payment-gateway/stripe.ts
> +    paymentOptions: TPaymentOptions,
used

2023-03-27 17:15 UTC, MatthewPattell requested changes

2023-03-27 17:15 UTC, MatthewPattell commented on microservices/payment/src/services/payment-gateway/stripe.ts
> +      throw new Error('Customer for this user already exists');
```suggestion
      throw new Error('Customer already exists.');
```

2023-03-27 17:15 UTC, MatthewPattell commented on microservices/payment/src/services/payment-gateway/stripe.ts
> +    this.paymentOptions = paymentOptions;
it should be in abstract

2023-03-27 17:15 UTC, MatthewPattell commented on microservices/payment/src/services/payment-gateway/stripe.ts
> +      throw new Error('Customer for this user already exists');
return customer instead error?

2023-03-27 17:15 UTC, MatthewPattell commented on microservices/payment/src/services/payment-gateway/stripe.ts
> +  constructor(
```suggestion
  /**
   * @constructor
   */
  constructor(
```

2023-03-27 17:15 UTC, MatthewPattell commented on microservices/payment/src/services/payment-gateway/stripe.ts
> +import IStripeOptions from '@interfaces/stripe-options';
```suggestion
import type IStripeOptions from '@interfaces/stripe-options';
```

2023-03-27 17:15 UTC, MatthewPattell commented on microservices/authorization/migrations/permissions/list/methods/payment.json
> +      "user"
```suggestion
      "admin"
```

2023-03-27 17:15 UTC, MatthewPattell commented on microservices/payment/src/services/payment-gateway/stripe.ts
> +    this.paymentOptions = paymentOptions;
```suggestion
```

2023-03-27 17:15 UTC, MatthewPattell commented on microservices/payment/src/services/payment-gateway/stripe.ts
> +
protected getCustomer()

2023-03-27 17:15 UTC, MatthewPattell commented on microservices/payment/src/services/payment-gateway/stripe.ts
> +      throw new Error('Customer for this user already exists');
```
public async createCustomer(userId: string): Promise<Customer> {
   const stripeCustomer: StripeSdk.Customer = await this.paymentEntity.customers.create();
  return super.createCustomer(userId, stripeCustomer.id);
}
```

2023-03-27 17:15 UTC, MatthewPattell commented on microservices/payment/src/services/payment-gateway/abstract.ts
> +
```
protected getCustomer() {
  const customer = await findOne();

  if (customer) {
      return customer;
  }

  const newCustomer = await this.createCustomer(usertId);

  return newCustomer;
}

public createCustomer(userId: string, customerId?: =uuidv4()) {
   const customer =  this.customerRepository.create({
      customerId,
      userId,
    });

  await repo.save(newCustomer)

 return customer;
}
```

2023-03-28 12:46 UTC, MatthewPattell approved these changes

2023-03-28 12:46 UTC, MatthewPattell commented on microservices/payment/src/services/payment-gateway/abstract.ts
> +  protected readonly paymentOptions: IStripeOptions;
```suggestion
  protected readonly paymentOptions: TPaymentOptions;
```

2023-03-28 16:13 UTC, MatthewPattell approved these changes

2023-03-28 16:13 UTC, merged